version: 0.1
phases:
  install:
    commands:
      - echo Entered the install phase...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Entering the build phase
      - echo Testing the scripts
      - echo Compilation Tests
      - python -m py_compile scripts/aviatrix_poller.py
      - python -m py_compile scripts/aviatrix_controller.py
      - python -m py_compile scripts/aviatrix_gateway.py
      - echo Run Unittest
      - python -m unittest discover scripts
