version: 0.1
phases:
  install:
    commands:
      - echo Entered the install phase...
  build:
    commands:
      - echo Entering the build phase
      - echo Testing the scripts
      - python -m unittest scripts/test_aviatrix_poller
