version: 0.1
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update
      - apt-get install -y zip curl
      - pip install -r requirements.txt
      - curl -s https://raw.githubusercontent.com/aws-quickstart/taskcat/master/installer/pip/pip3-install-master| python -E
  build:
    commands:
      - echo Entering the build phase...
      - echo Testing the scripts
      - echo Compilation Tests
      - python -m py_compile quickstart-aviatrix/scripts/aviatrix_poller.py
      - python -m py_compile quickstart-aviatrix/scripts/aviatrix_controller.py
      - python -m py_compile quickstart-aviatrix/scripts/aviatrix_gateway.py
      - echo Run Unittest
      - python -m unittest discover quickstart-aviatrix/scripts
      - echo Running taskcat
      - taskcat -c quickstart-aviatrix/ci/config.yml
  post_build:
    commands:
      - echo Entering the post_build phase...
      - cd $CODEBUILD_SRC_DIR/quickstart-aviatrix
      - chmod 444 quickstart-aviatrix/scripts/*
      - zip -j quickstart-aviatrix/scripts/aviatrix_controller.py.zip quickstart-aviatrix/scripts/aviatrix_controller.py quickstart-aviatrix/scripts/aviatrix.py quickstart-aviatrix/scripts/cfnresponse.py
      - zip -j quickstart-aviatrix/scripts/aviatrix_gateway.py.zip quickstart-aviatrix/scripts/aviatrix_gateway.py quickstart-aviatrix/scripts/aviatrix.py quickstart-aviatrix/scripts/cfnresponse.py
      - zip -j quickstart-aviatrix/scripts/aviatrix_poller.py.zip quickstart-aviatrix/scripts/aviatrix_poller.py
artifacts:
  files:
    - scripts/aviatrix_*.py.zip
    - templates/quickstart-aviatrix-*.template
  base-directory: quickstart-aviatrix
