version: 0.1
phases:
  install:
    commands:
      - echo Entered the install phase...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Entering the build phase
      - echo Testing the scripts
      - ls -lah
      - cd ./scripts
      - ls -lah
      - echo Compilation Tests
      - python -m py_compile aviatrix_poller.py
      - python -m py_compile aviatrix_controller.py
      - python -m py_compile aviatrix_gateway.py
      - echo Unittest
      - python -m unittest test_aviatrix_poller
