version: 0.1
phases:
  install:
    commands:
      - echo Entering the install phase...
      - apt-get update
      - apt-get install -y curl
      - curl -s https://raw.githubusercontent.com/aws-quickstart/taskcat/master/installer/pip/pip3-install-master| python -E
  build:
    commands:
      - echo Entering the build phase...
      - echo Running taskcat
      - taskcat -c quickstart-aviatrix/ci/config.yml
  post_build:
    commands:
      - echo Entering the post_build phase...
