---
- hosts: localhost
  connection: local
  tasks:
  - name: Check if the files compile
    shell: python ../quickstart-aviatrix/scripts/compile-test.py
    register: compile_output
  - debug:
      var: compile_output
  - name: Create aviatrix_controller.py.zip package
    archive:
      path:
          - ../quickstart-aviatrix/scripts/aviatrix_controller.py
          - ../quickstart-aviatrix/scripts/aviatrix.py
          - ../quickstart-aviatrix/scripts/cfnresponse.py
      dest: ./build/aviatrix_controller.py.zip
      format: zip
  - name: Create aviatrix_gateway.py.zip package
    archive:
      path:
          - ../quickstart-aviatrix/scripts/aviatrix_gateway.py
          - ../quickstart-aviatrix/scripts/aviatrix.py
      dest: ./build/aviatrix_gateway.py.zip
      format: zip
  - name: Create aviatrix_poller.py.zip package
    archive:
      path:
          - ../quickstart-aviatrix/scripts/aviatrix_poller.py
      dest: ./build/aviatrix_poller.py.zip
      format: zip
