---
- hosts: localhost
  connection: local
  tasks:
  - name: Create aviatrix_controller.py.zip package
    archive:
      path:
          - ../scripts/aviatrix_controller.py
          - ../scripts/aviatrix.py
          - ../scripts/cfn_resource.py
          - ../scripts/cfnresponse.py
      dest: ./build/aviatrix_controller.py.zip
      format: zip
  - name: Create aviatrix_gateway.py.zip package
    archive:
      path:
          - ../scripts/aviatrix_gateway.py
          - ../scripts/aviatrix.py
      dest: ./build/aviatrix_gateway.py.zip
      format: zip
  - name: Create aviatrix_poller.py.zip package
    archive:
      path:
          - ../scripts/aviatrix_poller.py
      dest: ./build/aviatrix_poller.py.zip
      format: zip
